 SET SERVEROUTPUT ON;

DECLARE 
CURSOR C1 IS 
    SELECT ENAME,DEPTNO,BASICSAL FROM EMP ORDER BY BASICSAL DESC;
    C1_ENAME EMP.ENAME%TYPE;
    C1_DEPTNO EMP.DEPTNO%TYPE;
    C1_BS EMP.BASICSAL%TYPE;

BEGIN 
    OPEN C1;

    LOOP 
        FETCH C1 INTO C1_ENAME,C1_DEPTNO,C1_BS;
        EXIT WHEN C1%NOTFOUND OR C1%ROWCOUNT > 5;
        DBMS_OUTPUT.PUT_LINE('Employee Name: '||C1_ENAME||' | Department Number: '||C1_DEPTNO||' | Basic Salary: '||C1_BS);
    END LOOP ;

    CLOSE C1;

    EXCEPTION 
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error: '||SQLERRM);
END;
/