CREATE TABLE CUSTOMER (
    ID NUMBER PRIMARY KEY,
    Name VARCHAR2(50),
    Address VARCHAR2(100)
);

INSERT INTO CUSTOMER VALUES (1, 'Alice', 'New York');
INSERT INTO CUSTOMER VALUES (2, 'Bob', 'London');
INSERT INTO CUSTOMER VALUES (3, 'Charlie', 'Delhi');
COMMIT;
